# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl:
title: itsjustmath.net
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: Observations and advice on navigating the ever-changing digital landscape.
author: Justin Mather
description: Observations and advice on navigating the ever-changing digital landscape.
markdown: kramdown
email: hello [at] itsjustmath [dot] net
url: "https://itsjustmath.net"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: America/Los_Angeles
excerpt_separator: <!--more-->
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "DeployToGithub.Rakefile",
    "README.md",
  ]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src
plugins:
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap
